version: '3.1'

services:
  db:
    image: mongo:latest
    restart: always
    container_name: solesearchpython-local-db
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
  elasticsearch:
    container_name: tqd-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - discovery.type=single-node
    logging:
      driver: none
    ports:
      - 9300:9300
      - 9200:9200

volumes:
  mongodata:
  esdata:
